### ISSUE TITLE
'kaaont:file' predicates can't be deleted. might be an escaping issue?

### ISSUE THREAD

**Issue by sfsheath** [kenchreai/kaa-data-entry#10]
See https://kenchreai-data-editor.herokuapp.com/detail/ke/ke1753 . If yo try to delete the File predicates, it won't work. Reload to see that they're still  there. I'm guessing this is an escaping issue. The object string isn't matching what's in the triplestore when the DELETE request is issued. But that's just a guess.

**Comment by BlaiseGratton** [comment]
@sfsheath issue was with the file predicates being considered as URIs instead of plain strings, so the db query was looking for e.g. `<photographs/ke/001.jpg>` instead of just `photographs/ke/001.jpg`, etc. I have removed the code that was wrapping the filename strings with angle brackets and tested on the test/test01 entity. Moving forward, will we want to consider files as URIs?

**Comment by sfsheath** [comment]
It's intentional that for now file names are literals. At some point we may promote each piece of media (image or other) to its own resource and give it a clean URI, but not in the near future. And I think we'd probably still keep a separate literal filename (even if exposed as a URL on web). For future discussion...
